#!/bin/bash

generate_file() {
cat <<EOF
// Code generated by go generate; DO NOT EDIT.
// This file was generated at
// $(date -u)
package main

import "github.com/hashicorp/nomad/nomad/structs"

var msgTypeNames = map[structs.MessageType]string{
EOF

  curl -sSL https://raw.githubusercontent.com/hashicorp/nomad/master/nomad/structs/structs.go \
  	| grep -A500 'NodeRegisterRequestType' \
  	| grep -v -e '//' \
  	| awk '/^\)$/ { exit; } /.*/ { printf "  structs.%s: \"%s\",\n", $1, $1}'

  echo '}'
}

generate_file > msgtypes.go

gofmt -w msgtypes.go
