// Code generated by go generate; DO NOT EDIT.
// This file was generated at
// Fri May 29 13:52:49 UTC 2020
package main

import "github.com/hashicorp/nomad/nomad/structs"

var msgTypeNames = map[structs.MessageType]string{
	structs.NodeRegisterRequestType:                 "NodeRegisterRequestType",
	structs.NodeDeregisterRequestType:               "NodeDeregisterRequestType",
	structs.NodeUpdateStatusRequestType:             "NodeUpdateStatusRequestType",
	structs.NodeUpdateDrainRequestType:              "NodeUpdateDrainRequestType",
	structs.JobRegisterRequestType:                  "JobRegisterRequestType",
	structs.JobDeregisterRequestType:                "JobDeregisterRequestType",
	structs.EvalUpdateRequestType:                   "EvalUpdateRequestType",
	structs.EvalDeleteRequestType:                   "EvalDeleteRequestType",
	structs.AllocUpdateRequestType:                  "AllocUpdateRequestType",
	structs.AllocClientUpdateRequestType:            "AllocClientUpdateRequestType",
	structs.ReconcileJobSummariesRequestType:        "ReconcileJobSummariesRequestType",
	structs.VaultAccessorRegisterRequestType:        "VaultAccessorRegisterRequestType",
	structs.VaultAccessorDeregisterRequestType:      "VaultAccessorDeregisterRequestType",
	structs.ApplyPlanResultsRequestType:             "ApplyPlanResultsRequestType",
	structs.DeploymentStatusUpdateRequestType:       "DeploymentStatusUpdateRequestType",
	structs.DeploymentPromoteRequestType:            "DeploymentPromoteRequestType",
	structs.DeploymentAllocHealthRequestType:        "DeploymentAllocHealthRequestType",
	structs.DeploymentDeleteRequestType:             "DeploymentDeleteRequestType",
	structs.JobStabilityRequestType:                 "JobStabilityRequestType",
	structs.ACLPolicyUpsertRequestType:              "ACLPolicyUpsertRequestType",
	structs.ACLPolicyDeleteRequestType:              "ACLPolicyDeleteRequestType",
	structs.ACLTokenUpsertRequestType:               "ACLTokenUpsertRequestType",
	structs.ACLTokenDeleteRequestType:               "ACLTokenDeleteRequestType",
	structs.ACLTokenBootstrapRequestType:            "ACLTokenBootstrapRequestType",
	structs.AutopilotRequestType:                    "AutopilotRequestType",
	structs.UpsertNodeEventsType:                    "UpsertNodeEventsType",
	structs.JobBatchDeregisterRequestType:           "JobBatchDeregisterRequestType",
	structs.AllocUpdateDesiredTransitionRequestType: "AllocUpdateDesiredTransitionRequestType",
	structs.NodeUpdateEligibilityRequestType:        "NodeUpdateEligibilityRequestType",
	structs.BatchNodeUpdateDrainRequestType:         "BatchNodeUpdateDrainRequestType",
}
